common.jvm.options=\
-Dfile.encoding=utf-8 \n\
-Djava.security.egd=file:/dev/./urandom \n\
-server \n\
-Xms1G \n\
-Xmx1G \n\
-XX:+UseG1GC \n\
-XX:MaxGCPauseMillis=300 \n\
-XX:ParallelGCThreads=8 \n\
-XX:ConcGCThreads=4 \n\
-XX:InitiatingHeapOccupancyPercent=35 \n\
-XX:+UnlockExperimentalVMOptions \n\
-XX:G1MixedGCCountTarget=4 \n\
-XX:G1OldCSetRegionThresholdPercent=20 \n\
-XX:MetaspaceSize=256m \n\
-XX:MaxMetaspaceSize=768m \n\
-XX:+UseTLAB \n\
-XX:TLABSize=256k \n\
-XX:+ResizeTLAB \n\
-XX:+PrintGCDetails \n\
-XX:+PrintGCDateStamps \n\
-XX:+PrintGCApplicationStoppedTime \n\
-Xloggc:./gc.log \n\
-XX:+UseGCLogFileRotation \n\
-XX:NumberOfGCLogFiles=10 \n\
-XX:GCLogFileSize=10M \n\
-XX:+DisableExplicitGC \n\
-XX:-UseBiasedLocking \n\

common.logging.config=\
<startmode>Automatic</startmode>${line.separator}\
<logpath>%BASE%\\serviceLogs</logpath>${line.separator}\
<log mode="roll-by-size">${line.separator}\
    <sizeThreshold>10240</sizeThreshold>${line.separator}\
    <keepFiles>8</keepFiles>${line.separator}\
</log>