-- ============================================================
-- WMS 基础数据引擎 V3 — 示例业务表 + 测试数据 + 元数据配置
-- ============================================================

-- 1. WMS_ITEM（物料表）
CREATE TABLE IF NOT EXISTS WMS_ITEM (
    ITEM_ID      INTEGER PRIMARY KEY,
    ITEM_CODE    VARCHAR(64) NOT NULL,
    ITEM_NAME    VARCHAR(128) NOT NULL,
    SPEC         VARCHAR(64),
    UNIT_ID      INTEGER,
    OWNER_ID     INTEGER,
    CATEGORY_ID  INTEGER,
    SUPPLIER_ID  INTEGER
);

-- 2. WMS_WAREHOUSE（仓库表）
CREATE TABLE IF NOT EXISTS WMS_WAREHOUSE (
    WAREHOUSE_ID    INTEGER PRIMARY KEY,
    WAREHOUSE_CODE  VARCHAR(64) NOT NULL,
    WAREHOUSE_NAME  VARCHAR(128) NOT NULL
);

-- 3. WMS_OWNER（货主表）
CREATE TABLE IF NOT EXISTS WMS_OWNER (
    OWNER_ID     INTEGER PRIMARY KEY,
    OWNER_CODE   VARCHAR(64) NOT NULL,
    OWNER_NAME   VARCHAR(128) NOT NULL
);

-- 4. WMS_UNIT（单位表）
CREATE TABLE IF NOT EXISTS WMS_UNIT (
    UNIT_ID     INTEGER PRIMARY KEY,
    UNIT_CODE   VARCHAR(64) NOT NULL,
    UNIT_NAME   VARCHAR(128) NOT NULL
);

-- 5. WMS_CATEGORY（分类表）
CREATE TABLE IF NOT EXISTS WMS_CATEGORY (
    CATEGORY_ID    INTEGER PRIMARY KEY,
    CATEGORY_CODE  VARCHAR(64) NOT NULL,
    CATEGORY_NAME  VARCHAR(128) NOT NULL
);

-- ============================================================
-- 插入测试数据
-- ============================================================

-- 仓库
INSERT INTO WMS_WAREHOUSE VALUES (1, 'WH01', '北京中心仓');
INSERT INTO WMS_WAREHOUSE VALUES (2, 'WH02', '上海中心仓');
INSERT INTO WMS_WAREHOUSE VALUES (3, 'WH03', '广州中心仓');

-- 货主
INSERT INTO WMS_OWNER VALUES (100, 'OW01', '华为终端');
INSERT INTO WMS_OWNER VALUES (200, 'OW02', '小米科技');
INSERT INTO WMS_OWNER VALUES (300, 'OW03', 'OPPO电子');

-- 单位
INSERT INTO WMS_UNIT VALUES (1, 'PCS', '个');
INSERT INTO WMS_UNIT VALUES (2, 'BOX', '箱');
INSERT INTO WMS_UNIT VALUES (3, 'KG', '千克');

-- 分类
INSERT INTO WMS_CATEGORY VALUES (10, 'CAT01', '电子产品');
INSERT INTO WMS_CATEGORY VALUES (20, 'CAT02', '食品饮料');
INSERT INTO WMS_CATEGORY VALUES (30, 'CAT03', '办公用品');

-- 物料
INSERT INTO WMS_ITEM VALUES (10001, 'ITEM001', '矿泉水500ml', '500ml', 1, 100, 20, 100);
INSERT INTO WMS_ITEM VALUES (10002, 'ITEM002', '手机壳', '通用', 1, 200, 10, 200);
INSERT INTO WMS_ITEM VALUES (10003, 'ITEM003', 'A4打印纸', '500张/包', 2, 300, 30, 300);
INSERT INTO WMS_ITEM VALUES (10004, 'ITEM004', '可乐330ml', '330ml', 1, 100, 20, 100);
INSERT INTO WMS_ITEM VALUES (10005, 'ITEM005', '充电器', '20W', 1, 200, 10, 200);

-- ============================================================
-- 插入元数据配置：BASE_DATA_ENTITY
-- ============================================================

INSERT INTO BASE_DATA_ENTITY (CACHE_NAME, ENTITY_NAME, TABLE_NAME, ID_COLUMN, CODE_COLUMN, CACHE_TYPE, TTL, MAX_CAPACITY, ENABLED, VERSION, SCHEMA_VERSION, SCHEMA_HASH) VALUES
    ('B_ITEM',      'Item',      'WMS_ITEM',      'ITEM_ID',      'ITEM_CODE',      'REDIS', 3600, 100000, TRUE, 1, 1, null),
    ('B_WAREHOUSE', 'Warehouse', 'WMS_WAREHOUSE', 'WAREHOUSE_ID', 'WAREHOUSE_CODE', 'REDIS', 7200, 20000,  TRUE, 1, 1, null),
    ('B_OWNER',     'Owner',     'WMS_OWNER',     'OWNER_ID',     'OWNER_CODE',     'REDIS', 7200, 20000,  TRUE, 1, 1, null),
    ('B_UNIT',      'Unit',      'WMS_UNIT',      'UNIT_ID',      'UNIT_CODE',      'REDIS', 7200, 10000,  TRUE, 1, 1, null),
    ('B_CATEGORY',  'Category',  'WMS_CATEGORY',  'CATEGORY_ID',  'CATEGORY_CODE',  'REDIS', 7200, 10000,  TRUE, 1, 1, null);

-- ============================================================
-- 插入元数据配置：BASE_DATA_FIELD
-- ============================================================

-- B_ITEM 字段
INSERT INTO BASE_DATA_FIELD (CACHE_NAME, COLUMN_NAME, DATA_TYPE, COLUMN_INDEX, NULLABLE, ENABLED, FIELD_VERSION, IS_ENCRYPTED) VALUES
    ('B_ITEM', 'ITEM_ID',     'INTEGER',    0, FALSE, TRUE, 1, FALSE),
    ('B_ITEM', 'ITEM_CODE',   'VARCHAR',    1, FALSE, TRUE, 1, FALSE),
    ('B_ITEM', 'ITEM_NAME',   'VARCHAR',    2, TRUE,  TRUE, 1, FALSE),
    ('B_ITEM', 'SPEC',        'VARCHAR',    3, TRUE,  TRUE, 1, FALSE),
    ('B_ITEM', 'UNIT_ID',     'INTEGER',    4, TRUE,  TRUE, 1, FALSE),
    ('B_ITEM', 'OWNER_ID',    'INTEGER',    5, TRUE,  TRUE, 1, FALSE),
    ('B_ITEM', 'CATEGORY_ID', 'INTEGER',    6, TRUE,  TRUE, 1, FALSE),
    ('B_ITEM', 'SUPPLIER_ID', 'INTEGER',    7, TRUE,  TRUE, 1, FALSE);

-- B_WAREHOUSE 字段
INSERT INTO BASE_DATA_FIELD (CACHE_NAME, COLUMN_NAME, DATA_TYPE, COLUMN_INDEX, NULLABLE, ENABLED, FIELD_VERSION, IS_ENCRYPTED) VALUES
    ('B_WAREHOUSE', 'WAREHOUSE_ID',    'INTEGER',  0, FALSE, TRUE, 1, FALSE),
    ('B_WAREHOUSE', 'WAREHOUSE_CODE',  'VARCHAR',  1, FALSE, TRUE, 1, FALSE),
    ('B_WAREHOUSE', 'WAREHOUSE_NAME',  'VARCHAR',  2, TRUE,  TRUE, 1, FALSE);

-- B_OWNER 字段
INSERT INTO BASE_DATA_FIELD (CACHE_NAME, COLUMN_NAME, DATA_TYPE, COLUMN_INDEX, NULLABLE, ENABLED, FIELD_VERSION, IS_ENCRYPTED) VALUES
    ('B_OWNER', 'OWNER_ID',    'INTEGER',  0, FALSE, TRUE, 1, FALSE),
    ('B_OWNER', 'OWNER_CODE',  'VARCHAR',  1, FALSE, TRUE, 1, FALSE),
    ('B_OWNER', 'OWNER_NAME',  'VARCHAR',  2, TRUE,  TRUE, 1, FALSE);

-- B_UNIT 字段
INSERT INTO BASE_DATA_FIELD (CACHE_NAME, COLUMN_NAME, DATA_TYPE, COLUMN_INDEX, NULLABLE, ENABLED, FIELD_VERSION, IS_ENCRYPTED) VALUES
    ('B_UNIT', 'UNIT_ID',    'INTEGER',  0, FALSE, TRUE, 1, FALSE),
    ('B_UNIT', 'UNIT_CODE',  'VARCHAR',  1, FALSE, TRUE, 1, FALSE),
    ('B_UNIT', 'UNIT_NAME',  'VARCHAR',  2, TRUE,  TRUE, 1, FALSE);

-- B_CATEGORY 字段
INSERT INTO BASE_DATA_FIELD (CACHE_NAME, COLUMN_NAME, DATA_TYPE, COLUMN_INDEX, NULLABLE, ENABLED, FIELD_VERSION, IS_ENCRYPTED) VALUES
    ('B_CATEGORY', 'CATEGORY_ID',    'INTEGER',  0, FALSE, TRUE, 1, FALSE),
    ('B_CATEGORY', 'CATEGORY_CODE',  'VARCHAR',  1, FALSE, TRUE, 1, FALSE),
    ('B_CATEGORY', 'CATEGORY_NAME',  'VARCHAR',  2, TRUE,  TRUE, 1, FALSE);

-- ============================================================
-- 插入元数据配置：BASE_DATA_RELATION（关联关系）
-- ============================================================

INSERT INTO BASE_DATA_RELATION (SOURCE_CACHE, SOURCE_COLUMN, TARGET_CACHE, TARGET_COLUMN, RELATION_TYPE, ENABLED) VALUES
    ('B_ITEM', 'UNIT_ID',     'B_UNIT',      'UNIT_ID',      'MANY_TO_ONE', TRUE),
    ('B_ITEM', 'OWNER_ID',    'B_OWNER',     'OWNER_ID',     'MANY_TO_ONE', TRUE),
    ('B_ITEM', 'CATEGORY_ID', 'B_CATEGORY',  'CATEGORY_ID',  'MANY_TO_ONE', TRUE);
