-- ============================================================
-- WMS BaseData Engine V3 — PostgreSQL DDL
-- 数据库: PostgreSQL (localhost:5432/postgres)
-- ============================================================

-- 1. BASE_DATA_ENTITY — 基础数据实体
CREATE TABLE BASE_DATA_ENTITY (
    CACHE_NAME        VARCHAR(64)    NOT NULL,
    ENTITY_NAME       VARCHAR(128)   NOT NULL,
    TABLE_NAME        VARCHAR(128)   NOT NULL,
    ID_COLUMN         VARCHAR(64)    NOT NULL,
    CODE_COLUMN       VARCHAR(64),
    CACHE_TYPE        VARCHAR(32)    DEFAULT 'REDIS' NOT NULL,
    TTL               INTEGER        DEFAULT 86400  NOT NULL,
    MAX_CAPACITY      INTEGER        DEFAULT 100000 NOT NULL,
    ENABLED           BOOLEAN        DEFAULT TRUE  NOT NULL,
    VERSION           INTEGER        DEFAULT 1     NOT NULL,
    SCHEMA_VERSION    INTEGER        DEFAULT 1     NOT NULL,
    SCHEMA_HASH       VARCHAR(64),
    UPDATE_TIME       TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_BASE_DATA_ENTITY PRIMARY KEY (CACHE_NAME)
);

COMMENT ON TABLE  BASE_DATA_ENTITY IS '基础数据实体元数据';
COMMENT ON COLUMN BASE_DATA_ENTITY.CACHE_NAME     IS '缓存名称，如 B_ITEM';
COMMENT ON COLUMN BASE_DATA_ENTITY.ENTITY_NAME    IS '实体类名，如 Item';
COMMENT ON COLUMN BASE_DATA_ENTITY.TABLE_NAME     IS '数据库表名，如 wms_item';
COMMENT ON COLUMN BASE_DATA_ENTITY.ID_COLUMN      IS '主键列名，如 item_id';
COMMENT ON COLUMN BASE_DATA_ENTITY.CODE_COLUMN    IS '编码列名（可空）';
COMMENT ON COLUMN BASE_DATA_ENTITY.CACHE_TYPE     IS '缓存类型：REDIS / LOCAL / HYBRID';
COMMENT ON COLUMN BASE_DATA_ENTITY.TTL            IS 'Redis TTL（秒）';
COMMENT ON COLUMN BASE_DATA_ENTITY.MAX_CAPACITY   IS 'Caffeine 最大条数';
COMMENT ON COLUMN BASE_DATA_ENTITY.SCHEMA_VERSION IS 'Schema 版本号，字段增删改时 +1';
COMMENT ON COLUMN BASE_DATA_ENTITY.SCHEMA_HASH    IS 'Schema 哈希';

-- 2. BASE_DATA_FIELD — 字段元数据
CREATE TABLE BASE_DATA_FIELD (
    CACHE_NAME        VARCHAR(64)    NOT NULL,
    COLUMN_NAME       VARCHAR(64)    NOT NULL,
    DATA_TYPE         VARCHAR(32)    NOT NULL,
    DATA_LENGTH       INTEGER,
    DATA_PRECISION    INTEGER,
    DATA_SCALE        INTEGER,
    NULLABLE          BOOLEAN        DEFAULT TRUE NOT NULL,
    COLUMN_INDEX      INTEGER        NOT NULL,
    ENABLED           BOOLEAN        DEFAULT TRUE NOT NULL,
    FIELD_VERSION     INTEGER        DEFAULT 1    NOT NULL,
    IS_ENCRYPTED      BOOLEAN        DEFAULT FALSE NOT NULL,
    FIELD_TTL         INTEGER,
    CONSTRAINT PK_BASE_DATA_FIELD PRIMARY KEY (CACHE_NAME, COLUMN_NAME)
);

COMMENT ON TABLE  BASE_DATA_FIELD IS '基础数据字段元数据';
COMMENT ON COLUMN BASE_DATA_FIELD.COLUMN_INDEX   IS '字段在 CompactRow.values[] 中的下标';
COMMENT ON COLUMN BASE_DATA_FIELD.IS_ENCRYPTED   IS 'TRUE=敏感字段加密存储';
COMMENT ON COLUMN BASE_DATA_FIELD.FIELD_TTL      IS '字段级 TTL（空=用实体默认 TTL）';

-- 3. BASE_DATA_RELATION — 关联关系
CREATE TABLE BASE_DATA_RELATION (
    SOURCE_CACHE      VARCHAR(64)    NOT NULL,
    SOURCE_COLUMN     VARCHAR(64)    NOT NULL,
    TARGET_CACHE      VARCHAR(64)    NOT NULL,
    TARGET_COLUMN     VARCHAR(64)    NOT NULL,
    RELATION_TYPE     VARCHAR(32)    DEFAULT 'MANY_TO_ONE' NOT NULL,
    ENABLED           BOOLEAN        DEFAULT TRUE NOT NULL,
    CONSTRAINT PK_BASE_DATA_RELATION PRIMARY KEY (SOURCE_CACHE, SOURCE_COLUMN, TARGET_CACHE)
);

COMMENT ON TABLE  BASE_DATA_RELATION IS '基础数据关联关系（第一版只支持 1:1 / N:1）';

-- 4. BASE_DATA_PROJECTION — 字段投影
CREATE TABLE BASE_DATA_PROJECTION (
    CACHE_NAME        VARCHAR(64)    NOT NULL,
    PROJECTION_NAME   VARCHAR(32)    NOT NULL,
    FIELDS            TEXT           NOT NULL,
    ENABLED           BOOLEAN        DEFAULT TRUE NOT NULL,
    CONSTRAINT PK_BASE_DATA_PROJECTION PRIMARY KEY (CACHE_NAME, PROJECTION_NAME)
);

COMMENT ON TABLE  BASE_DATA_PROJECTION IS '字段投影配置';
COMMENT ON COLUMN BASE_DATA_PROJECTION.FIELDS IS '字段名 JSON 数组，如 ["ITEM_ID","ITEM_CODE","ITEM_NAME"]';

-- 5. BASE_DATA_CACHE — 缓存策略
CREATE TABLE BASE_DATA_CACHE (
    CACHE_NAME             VARCHAR(64)    NOT NULL,
    CACHE_TYPE             VARCHAR(32)    DEFAULT 'REDIS'     NOT NULL,
    TTL                    INTEGER        DEFAULT 86400        NOT NULL,
    MAX_CAPACITY           INTEGER        DEFAULT 100000       NOT NULL,
    ENABLE_LOCAL_CACHE     BOOLEAN        DEFAULT TRUE         NOT NULL,
    ENABLE_NULL_CACHE      BOOLEAN        DEFAULT TRUE         NOT NULL,
    ENABLE_PREWARM         BOOLEAN        DEFAULT FALSE        NOT NULL,
    ENABLE_PROTECTION      BOOLEAN        DEFAULT TRUE         NOT NULL,
    BATCH_SIZE             INTEGER        DEFAULT 1000         NOT NULL,
    RANDOM_TTL             BOOLEAN        DEFAULT TRUE         NOT NULL,
    MAX_RELATION_DEPTH     SMALLINT       DEFAULT 5            NOT NULL,
    NULL_TTL               INTEGER        DEFAULT 60           NOT NULL,
    LOCK_TIMEOUT_MS        INTEGER        DEFAULT 3000         NOT NULL,
    ENABLE_SWR             BOOLEAN        DEFAULT TRUE         NOT NULL,
    SWR_REFRESH_TTL        INTEGER        DEFAULT 7200         NOT NULL,
    ENABLE_CIRCUIT_BREAKER BOOLEAN        DEFAULT TRUE         NOT NULL,
    CB_FAILURE_THRESHOLD   SMALLINT       DEFAULT 10           NOT NULL,
    CB_RECOVERY_MS         INTEGER        DEFAULT 30000        NOT NULL,
    ADMISSION_THRESHOLD    SMALLINT       DEFAULT 3            NOT NULL,
    MAX_BATCH_IDS          INTEGER        DEFAULT 2000         NOT NULL,
    MAX_RESULT_ROWS        INTEGER        DEFAULT 5000         NOT NULL,
    MAX_PAYLOAD_BYTES      INTEGER        DEFAULT 5242880      NOT NULL,
    CONSISTENCY_LEVEL      VARCHAR(16)    DEFAULT 'EVENTUAL'   NOT NULL,
    DEGRADE_POLICY         VARCHAR(16)    DEFAULT 'FAIL_FAST'  NOT NULL,
    REVISION_STRATEGY      VARCHAR(16)    DEFAULT 'NONE'       NOT NULL,
    CONSTRAINT PK_BASE_DATA_CACHE PRIMARY KEY (CACHE_NAME)
);

COMMENT ON TABLE  BASE_DATA_CACHE IS '缓存策略配置';
COMMENT ON COLUMN BASE_DATA_CACHE.RANDOM_TTL          IS 'TRUE=启用 TTL 随机偏移防雪崩';
COMMENT ON COLUMN BASE_DATA_CACHE.MAX_RELATION_DEPTH  IS '关联递归最大深度';
COMMENT ON COLUMN BASE_DATA_CACHE.CONSISTENCY_LEVEL   IS 'EVENTUAL / STRONGER / BYPASS_CACHE';
COMMENT ON COLUMN BASE_DATA_CACHE.DEGRADE_POLICY      IS 'FAIL_FAST / PARTIAL / RETURN_STALE / BYPASS_CACHE';
COMMENT ON COLUMN BASE_DATA_CACHE.REVISION_STRATEGY   IS 'NONE / ROW_VERSION / SEQUENCE_VERSION / UPDATE_TIME';

-- 6. BASE_DATA_SCHEMA_CHANGE — Schema 变更记录
CREATE TABLE BASE_DATA_SCHEMA_CHANGE (
    CHANGE_ID         BIGINT        NOT NULL,
    CACHE_NAME        VARCHAR(64)   NOT NULL,
    OLD_VERSION       INTEGER,
    NEW_VERSION       INTEGER       NOT NULL,
    CHANGE_TYPE       VARCHAR(32)   NOT NULL,
    CHANGE_DETAIL     TEXT,
    SCHEMA_HASH_OLD   VARCHAR(64),
    SCHEMA_HASH_NEW   VARCHAR(64),
    CREATE_TIME       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_BASE_DATA_SCHEMA_CHANGE PRIMARY KEY (CHANGE_ID)
);

COMMENT ON TABLE  BASE_DATA_SCHEMA_CHANGE IS 'Schema 变更历史';
COMMENT ON COLUMN BASE_DATA_SCHEMA_CHANGE.CHANGE_TYPE IS 'ADD_COLUMN / DROP_COLUMN / TYPE_CHANGE / LENGTH_CHANGE / NULLABLE_CHANGE';

-- 7. CACHE_EVENT_OUTBOX — 事件 Outbox
CREATE TABLE CACHE_EVENT_OUTBOX (
    EVENT_ID          BIGINT        NOT NULL,
    EVENT_TYPE        VARCHAR(64)   NOT NULL,
    CACHE_NAME        VARCHAR(64),
    SCHEMA_VERSION    INTEGER,
    IDS               TEXT,
    STATUS            VARCHAR(16)   DEFAULT 'PENDING' NOT NULL,
    RETRY_COUNT       SMALLINT      DEFAULT 0         NOT NULL,
    MAX_RETRY         SMALLINT      DEFAULT 3         NOT NULL,
    CREATE_TIME       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_CACHE_EVENT_OUTBOX PRIMARY KEY (EVENT_ID)
);

CREATE INDEX IDX_OUTBOX_STATUS ON CACHE_EVENT_OUTBOX (STATUS, CREATE_TIME);

COMMENT ON TABLE  CACHE_EVENT_OUTBOX IS '缓存事件 Outbox（与业务更新同事务写入）';
COMMENT ON COLUMN CACHE_EVENT_OUTBOX.EVENT_TYPE IS 'CACHE_INVALIDATE_BATCH / SCHEMA_CHANGED';
COMMENT ON COLUMN CACHE_EVENT_OUTBOX.IDS        IS '失效 ID JSON 数组';
COMMENT ON COLUMN CACHE_EVENT_OUTBOX.STATUS     IS 'PENDING / SENT / DONE / FAILED';

-- 8. BASE_DATA_CONFIG_AUDIT — 配置审计
CREATE TABLE BASE_DATA_CONFIG_AUDIT (
    AUDIT_ID          BIGINT        NOT NULL,
    CACHE_NAME        VARCHAR(64),
    OPERATION         VARCHAR(32)   NOT NULL,
    OLD_CONFIG        TEXT,
    NEW_CONFIG        TEXT,
    VERSION           INTEGER,
    PUBLISH_RESULT    VARCHAR(16),
    ERROR_MESSAGE     TEXT,
    OPERATOR          VARCHAR(64),
    CREATE_TIME       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_BASE_DATA_CONFIG_AUDIT PRIMARY KEY (AUDIT_ID)
);

COMMENT ON TABLE BASE_DATA_CONFIG_AUDIT IS 'Metadata 配置审计';

-- 9. 序列（PostgreSQL 用 SEQUENCE）
CREATE SEQUENCE IF NOT EXISTS SEQ_SCHEMA_CHANGE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_OUTBOX_EVENT  START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_CONFIG_AUDIT  START WITH 1 INCREMENT BY 1;

-- ============================================================
-- 初始数据：标准 Projection
-- ============================================================

INSERT INTO BASE_DATA_PROJECTION (CACHE_NAME, PROJECTION_NAME, FIELDS, ENABLED) VALUES
    ('B_ITEM', 'FULL',   '["ITEM_ID","ITEM_CODE","ITEM_NAME","SPEC","UNIT_ID","OWNER_ID","CATEGORY_ID","SUPPLIER_ID"]', TRUE),
    ('B_ITEM', 'SIMPLE', '["ITEM_ID","ITEM_CODE","ITEM_NAME"]', TRUE),
    ('B_ITEM', 'PDA',    '["ITEM_ID","ITEM_CODE","ITEM_NAME","UNIT_ID"]', TRUE),
    ('B_ITEM', 'LIST',   '["ITEM_ID","ITEM_CODE","ITEM_NAME","SPEC"]', TRUE);

INSERT INTO BASE_DATA_PROJECTION (CACHE_NAME, PROJECTION_NAME, FIELDS, ENABLED) VALUES
    ('B_OWNER', 'FULL',   '["OWNER_ID","OWNER_CODE","OWNER_NAME"]', TRUE),
    ('B_OWNER', 'SIMPLE', '["OWNER_ID","OWNER_CODE","OWNER_NAME"]', TRUE);

INSERT INTO BASE_DATA_PROJECTION (CACHE_NAME, PROJECTION_NAME, FIELDS, ENABLED) VALUES
    ('B_WAREHOUSE', 'FULL',   '["WAREHOUSE_ID","WAREHOUSE_CODE","WAREHOUSE_NAME"]', TRUE),
    ('B_WAREHOUSE', 'SIMPLE', '["WAREHOUSE_ID","WAREHOUSE_CODE","WAREHOUSE_NAME"]', TRUE);

INSERT INTO BASE_DATA_PROJECTION (CACHE_NAME, PROJECTION_NAME, FIELDS, ENABLED) VALUES
    ('B_UNIT', 'FULL',   '["UNIT_ID","UNIT_CODE","UNIT_NAME"]', TRUE),
    ('B_UNIT', 'SIMPLE', '["UNIT_ID","UNIT_CODE","UNIT_NAME"]', TRUE);

INSERT INTO BASE_DATA_PROJECTION (CACHE_NAME, PROJECTION_NAME, FIELDS, ENABLED) VALUES
    ('B_CATEGORY', 'FULL',   '["CATEGORY_ID","CATEGORY_CODE","CATEGORY_NAME"]', TRUE),
    ('B_CATEGORY', 'SIMPLE', '["CATEGORY_ID","CATEGORY_CODE","CATEGORY_NAME"]', TRUE);

-- 初始缓存策略
INSERT INTO BASE_DATA_CACHE (CACHE_NAME, CACHE_TYPE, TTL, MAX_CAPACITY, ENABLE_LOCAL_CACHE, ENABLE_NULL_CACHE, ENABLE_PREWARM, ENABLE_PROTECTION, BATCH_SIZE, RANDOM_TTL, MAX_RELATION_DEPTH, NULL_TTL, LOCK_TIMEOUT_MS, ENABLE_SWR, SWR_REFRESH_TTL, ENABLE_CIRCUIT_BREAKER, CB_FAILURE_THRESHOLD, CB_RECOVERY_MS, ADMISSION_THRESHOLD, MAX_BATCH_IDS, MAX_RESULT_ROWS, MAX_PAYLOAD_BYTES, CONSISTENCY_LEVEL, DEGRADE_POLICY, REVISION_STRATEGY) VALUES
    ('B_ITEM', 'REDIS', 3600, 100000, TRUE, TRUE, FALSE, TRUE, 1000, TRUE, 5, 60, 3000, TRUE, 7200, TRUE, 10, 30000, 3, 2000, 5000, 5242880, 'EVENTUAL', 'FAIL_FAST', 'NONE'),
    ('B_OWNER', 'REDIS', 7200, 20000, TRUE, TRUE, TRUE, TRUE, 1000, TRUE, 3, 60, 3000, TRUE, 7200, TRUE, 10, 30000, 2, 2000, 5000, 5242880, 'EVENTUAL', 'FAIL_FAST', 'NONE'),
    ('B_WAREHOUSE', 'REDIS', 7200, 10000, TRUE, TRUE, TRUE, TRUE, 1000, TRUE, 3, 60, 3000, TRUE, 7200, TRUE, 10, 30000, 2, 2000, 5000, 5242880, 'EVENTUAL', 'FAIL_FAST', 'NONE'),
    ('B_UNIT', 'REDIS', 7200, 10000, TRUE, TRUE, TRUE, TRUE, 1000, TRUE, 2, 60, 3000, TRUE, 7200, TRUE, 10, 30000, 2, 2000, 5000, 5242880, 'EVENTUAL', 'FAIL_FAST', 'NONE'),
    ('B_CATEGORY', 'REDIS', 7200, 10000, TRUE, TRUE, TRUE, TRUE, 1000, TRUE, 3, 60, 3000, TRUE, 7200, TRUE, 10, 30000, 2, 2000, 5000, 5242880, 'EVENTUAL', 'FAIL_FAST', 'NONE');
